### ISSUE TITLE
Build on nightly failed

### ISSUE THREAD

**Issue by balroggg** [Xithrius/twitch-tui#133]
Probably not important, but easy to fix.

Build on nightly failed (1.62.0-nightly (f4ec0e7cf 2022-04-22))
```
cargo +nightly c
    Checking twitch-tui v2.0.0-alpha.3 (/home/balrog/src/twitch-tui)
error[E0283]: type annotations needed
  --> src/ui/mod.rs:62:35
```
Possible fix:
```diff
diff --git a/src/ui/mod.rs b/src/ui/mod.rs
index f32f5b7..681b8e3 100644
--- a/src/ui/mod.rs
+++ b/src/ui/mod.rs
@@ -51,7 +51,7 @@ pub fn draw_ui<T: Backend>(frame: &mut Frame<T>, app: &mut App, config: &Complet
     let vertical_chunks = Layout::default()
         .direction(Direction::Vertical)
         .margin(margin)
-        .constraints(vertical_chunk_constraints.as_ref())
+        .constraints(vertical_chunk_constraints.as_slice())
         .split(frame.size());
```

**Comment by Xithrius** [comment]
What are your thoughts on moving this project to nightly builds?

I am unsure myself, as I don't run nightly.

**Comment by balroggg** [comment]
It's only a proposal for the future or limitation of tui.
Nightly builds are unstable, I don't think the project or users win from this . Each iteration of the compiler gains a little bit of speed (around 1-2% what I saw), not so many. For myself, I just change the default linker and that's all.

Feel free to close this issue if you want.

**Comment by Xithrius** [comment]
I don't think we need to focus on nightly at this current time, but I'll definitely think about this for the future.

Thanks for bringing it up!
